### ISSUE TITLE
ambig set bug from Soumya

### ISSUE THREAD

**Issue by annashcherbina** [kundajelab/seqdataloader#6]
Traceback (most recent call last):
  File "preprocess.py", line 24, in <module>
    genomewide_labels(train_set_params)
  File "/srv/scratch/soumyak/seqdataloader/seqdataloader/__init__.py", line 275, in genomewide_labels
    processed_chrom_outputs=pool.map(get_chrom_labels,pool_args)
  File "/srv/scratch/soumyak/miniconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/srv/scratch/soumyak/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/srv/scratch/soumyak/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/srv/scratch/soumyak/miniconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/srv/scratch/soumyak/seqdataloader/seqdataloader/__init__.py", line 101, in get_chrom_labels
    bin_values=pool.map(get_labels_one_task,pool_inputs)
  File "/srv/scratch/soumyak/miniconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/srv/scratch/soumyak/miniconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/srv/scratch/soumyak/miniconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/srv/scratch/soumyak/miniconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/srv/scratch/soumyak/seqdataloader/seqdataloader/__init__.py", line 68, in get_labels_one_task
    return labeling_approaches[args.labeling_approach](task_name,task_bed,task_bigwig,task_ambig,chrom,first_coord,final_coord,args)    
  File "/srv/scratch/soumyak/seqdataloader/seqdataloader/regression_label_protocols.py", line 176, in all_genome_bins_regression
    if ((args.allow_ambiguous==True) and (task_ambig!=None)):
  File "/srv/scratch/soumyak/miniconda3/lib/python3.7/site-packages/pybedtools/bedtool.py", line 1158, in __ne__
    return not self.__eq__(other)
  File "/srv/scratch/soumyak/miniconda3/lib/python3.7/site-packages/pybedtools/bedtool.py", line 1153, in __eq__
    if str(self) == str(other):
  File "/srv/scratch/soumyak/miniconda3/lib/python3.7/site-packages/pybedtools/bedtool.py", line 1134, in __str__
    for i in iter(self):
  File "pybedtools/cbedtools.pyx", line 754, in pybedtools.cbedtools.IntervalIterator.__next__
TypeError: float object is not an iterator
Col

with open("AD_ADAD_CAUD.task.tsv",'w') as f:
    f.write("AD_ADAD_CAUD\tAD_ADAD_CAUD.narrowpeak.gz\tAD_ADAD_CAUD.fc.signal.bigwig\tNaN\n")

train_set_params={
    'task_list':"AD_ADAD_CAUD.task.tsv",
    'outf':"AD_ADAD_CAUD.train.regression.hdf5",
    'output_type':'hdf5',
    'chrom_sizes':'hg38.chrom.sizes',
    'store_values_above_thresh': 0,
    'chroms_to_exclude':['chr1','chr2','chr19','chrY'],
    'bin_stride':50,
    'left_flank':400,
    'right_flank':400,
    'bin_size':200,
    'threads':10,
    'subthreads':4,
    'labeling_approach':'all_genome_bins_regression'
    }
genomewide_labels(train_set_params)

**Comment by annashcherbina** [comment]
fixed
